
// © yogoru 

//@version=5

indicator("OKO - SM", overlay = true 
  , max_labels_count = 500
  , max_lines_count = 500
  , max_boxes_count = 500
  , max_bars_back = 500)


showAlerts = input.bool(true, "Alerts", group = "Show settings",inline = "01")
scalpingAlerts = input.bool(true, "Scalping", group = "Show settings", inline = "01")
showPivots = input.bool(true, "Pivots", group = "Show settings",inline = "01")

showOrderBlocks = input.bool(true, "Order Blocks", group = "Show settings",inline = "02")
showChannel = input.bool(true, "Channel", group = "Show settings",inline = "02")
show3orMore = input.bool(true, "3 or More", group = "Show settings",inline = "02")

// showBBinput = input.bool(true, "BB", group = "Show settings",inline = "02")

i_zigZag     = input.bool(true, "Waves", group = "Show settings", inline = "03")
showCmaLines = input.bool(true, "CMA", group = "Show settings",inline = "03")
showBarColor = input.bool(true, "Bar Colors", group = "Show settings",inline = "03")
showTrendLine = input.bool(true, "Trend line", group = "Show settings",inline = "03")

/////////////////////////////////
//WICK.ed
// Define "n" as the number of periods and keep a minimum value of 2 for error handling.
n1 = input.int(title="Periods", defval=2, minval=2) 
fractalBars = input.int(title="3 or 5 Bar Fractal", defval=3, options=[3, 5])

// Logic 
dnFractal = if fractalBars == 5 
    (high[n1-2] < high[n1]) and (high[n1-1] < high[n1]) and (high[n1+1] < high[n1]) and (high[n1+2] < high[n1])
else
    (high[n1-1] < high[n1]) and (high[n1+1] < high[n1]) 

upFractal = if fractalBars == 5 
    (low[n1-2] > low[n1]) and (low[n1-1] > low[n1]) and (low[n1+1] > low[n1]) and (low[n1+2] > low[n1])
else
    (low[n1-1] > low[n1]) and (low[n1+1] > low[n1]) 

// Plot the fractals as shapes on the chart.
// Down Arrow above candles 
plotshape(dnFractal, style=shape.triangledown, location=location.abovebar, offset=-2, color=color.new(color.white, 25))    
// Up Arrow below candles 
plotshape(upFractal, style=shape.triangleup, location=location.belowbar, offset=-2, color=color.new(color.white, 25))// END. 



// 3 OR MORE
///////////////////////////////////////////

bull_candle = close - open > 0
bear_candle = close - open < 0


tc = close[2] - open[2] > 0 //thirdcandle
sc = close[1] - open[1] > 0 //second candle
fc = close - open > 0 //first candle
threesame = tc == sc and sc == fc and tc == fc

three_bull = bull_candle and threesame
three_bear = bear_candle and threesame

barcolor(show3orMore and three_bear? #dc3030: show3orMore and three_bull? #56a656 : na,-2)
barcolor(show3orMore and three_bear? #dc3030: show3orMore and three_bull? #56a656: na,-1)
barcolor(show3orMore and three_bear? #dc3030: show3orMore and three_bull? #56a656 : na) 

// 3 OR MORE
///////////////////////////////////////////


float factor = input.float(1,title="Activity", step=0.1, inline = "Alerts", group = "Alerts Setings"  )
int pd = input.int(43,title="Volatility", minval = 1, maxval = 100,inline = "Alerts", group = "Alerts Setings")
float up = hl2 - (factor * ta.atr(pd))
dn = hl2 + (factor * ta.atr(pd))

float trendup = 0.0
float trenddown = 0.0
float trendX = 0.0

trendup := hl2[1] > trendup[1] ? math.max(up, trendup[1]) : up
trenddown := hl2[1] < trenddown[1] ? math.min(dn, trenddown[1]) : dn
trendX := hl2 > trenddown[1] ? 1 : hl2 < trendup[1] ? -1 : nz(trendX[1], 1)
tsl = trendX == 1 ? trendup : trenddown
color linecolor = trendX == 1 ? color.green : color.red


// ///////////////////////////////////////////////////////////// -- PIVOTS -- ////////////////////////////////////////////////////////

// -- verbose resolution options.
i_res0  = "1 Hour",     i_res1  = "2 Hour",     i_res2  = "3 Hour"
i_res3  = "4 Hour",     i_res4  = "6 Hour",     i_res5  = "12 Hour"
i_res6  = "1 Day",      i_res7  = "5 Day",      i_res8  = "1 Week"
i_res9  = "1 Month",    i_res10 = "3 Month",    i_res11 = "6 Month"
i_res12 = "1 Year"

// -- pivot options
i_piv0  = "Traditional"


// -- line style options.
i_line0 = "Solid",      i_line1 = "Dotted",     i_line2 = "Dashed"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//                     ====== VAR and ARRAY PRESET ======                     //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

// -- Preset INT for maximum amount of S|R levels for any single pivot type.
// NOTE - this variable should only be changed if:
//  • you extend a pivot to have more than 5 levels of S|R
//  • you add a new pivot type wiith more than 5 levels of S|R
var int i_maxLevels = 5

// -- Preset INT for max length of pivot arrays [PP + S max + R max]
//  * NOTE: should not be changed.
var int i_maxLength = 1 + ( i_maxLevels * 2 )

// -- Initiate arrays to contain INT variables used in drawing function
//    settings, we fill these at the end of the INPUTS section.
var int[] i_settingsA = array.new_int(3, 0)
var int[] i_settingsB = array.new_int(3, 0)
var int[] i_settingsC = array.new_int(3, 0)

// -- Pivots A Main Settings -- 

INP_resolutionA = input.string( i_res6, " ",
      inline = "line1",   group = "Pivot Settings",
      options = [ i_res0, i_res1, i_res2, i_res3, i_res4, i_res5, i_res6, i_res7, i_res8, i_res9, i_res10, i_res11, i_res12
      ])
INP_showPivotsA = input( true, "", inline = "line1", group = "Pivot Settings")
INP_supportsA   = input.int( 3, "S/R Pivots", inline = "line1",   group = "Pivot Settings", minval = 0, maxval = i_maxLevels)
INP_flavourA    = i_piv0
INP_resistsA    = INP_supportsA
// -- Pivots B Main Settings

INP_resolutionB = input.string( i_res8, " ",
      inline = "line2", group = "Pivot Settings",
      options = [ i_res0, i_res1, i_res2, i_res3, i_res4, i_res5, i_res6, i_res7, i_res8, i_res9, i_res10, i_res11, i_res12
      ])
INP_showPivotsB = input( false, "", inline = "line2", group = "Pivot Settings")
INP_supportsB   = input.int( 3, "S/R Pivots", inline = "line2", group = "Pivot Settings", minval = 0, maxval = i_maxLevels)
INP_flavourB    = i_piv0
INP_resistsB    = INP_supportsB

// -- Pivots C Main Settings

INP_resolutionC = input.string( i_res9, " ",
      inline = "line3",
      group = "Pivot Settings",
      options = [ i_res0, i_res1, i_res2, i_res3, i_res4, i_res5, i_res6, i_res7, i_res8, i_res9, i_res10, i_res11, i_res12
      ])
INP_showPivotsC = input( false, "", inline = "line3", group = "Pivot Settings")
INP_supportsC   = input.int( 3, "S/R Pivots", inline = "line3", group = "Pivot Settings", minval = 0, maxval = i_maxLevels )
INP_flavourC    = i_piv0
INP_resistsC    = INP_supportsC
// ///////////////////////////////////////////////////////////// -- PIVOTS -- ////////////////////////////////////////////////////////



// /////////////////////////////////////////////////////// --ORDER BLOCKS-- ////////////////////////////////////////////////////////


// // Input options
// ranges = input.int(title="Candle Range",defval=26, minval=5, maxval=100, group="Order Block's settings", inline = "01")
// bearishOBColour = input(title="", defval=color.rgb(255,0,0, 90), group="Order Block's settings", inline = "01")
// bullishOBColour = input(title="", defval=color.rgb(0,255,0, 90), group="Order Block's settings", inline = "01")

// // showOrderBlocks

// // candle colouring
// var int CandleColourMode = 0
// var bool BosCandle = false

// // tracking for entries
// var int lastDownIndex=0
// var float lastDown=0
// var float lastLow=0

// var int lastUpIndex=0
// var float lastUp=0
// var float lastUpLow=0
// var float lastUpOpen=0
// var float lastHigh=0
// var float lastBullBreakLow=0

// // structure
// var int structureLowIndex=0
// float structureLow=1000000

// // order block drawing arrays

// var longBoxes = array.new_box()
// var shortBoxes = array.new_box()

// var int lastLongIndex=0
// var int lastShortIndex=0

// BosCandle:=true

// var int AlertCondition = 0

// AlertCondition:=0


// // get the lowest point in the range
// structureLow:=ta.lowest(low, ranges)[1]

// // bearish break of structure
// if(ta.crossunder(low,structureLow))
//     if((bar_index - lastUpIndex) < 1000 and bar_index>lastShortIndex  and showOrderBlocks)
//         // add bear order block
//         array.push(shortBoxes,box.new(left=lastUpIndex, top=lastHigh, bottom=lastUpLow,right=lastUpIndex, bgcolor=bearishOBColour,border_color=bearishOBColour, extend=extend.right))
//         // show bos candle
//         BosCandle:=true
//         // alert if change in direction on break
//         if(CandleColourMode==1)
//             AlertCondition:=1
//         // color mode bear
//         CandleColourMode:=0
//         // update last short index to prevent duplication
//         lastShortIndex:=bar_index
//         // alert
//         alert("Bearish break in structure",alert.freq_once_per_bar)


// // bullish break of structure?
// if((array.size(shortBoxes)>0))
//     for i = (array.size(shortBoxes)-1) to 0
//         box=array.get(shortBoxes,i)
//         top=box.get_top(box)
//         if(close>top and close>(ta.ema(high,50)))
//             // remove the short box 
//             box.delete(box)
//             array.remove(shortBoxes, i)
//             // ok to draw?
//             if((bar_index - lastDownIndex) < 1000 and bar_index>lastLongIndex)
//                 // add bullish order block
//                 array.push(longBoxes, box.new(left=lastDownIndex, top=lastDown, bottom=lastLow,right=lastDownIndex, bgcolor=bullishOBColour,border_color=bullishOBColour, extend=extend.right))
//                 // show bos candle
//                 BosCandle:=true
//                 // colour mode bullish
//                 CandleColourMode:=1
//                 // record last bull bar index to prevent duplication
//                 lastLongIndex:=bar_index
//                 lastBullBreakLow:=low
//                 // alert
//                 alert("Bullish break in structure",alert.freq_once_per_bar)


// // remove LL if close below
// if((array.size(longBoxes) > 0))
//     for i = (array.size(longBoxes)-1) to 0
//         lbox=array.get(longBoxes,i)
//         bottom=box.get_bottom(lbox)
//         top=box.get_top(lbox)
//         if(close<bottom)
//             array.remove(longBoxes, i)
//             box.delete(lbox)


// // record last up and down candles
// if(close<open)
//     lastDown:=high
//     lastDownIndex:=bar_index
//     lastLow:=low

// if(close>open)
//     lastUp:=close
//     lastUpIndex:=bar_index
//     lastUpOpen:=open
//     lastUpLow:=low
//     lastHigh:=high
    
// // update last high/low for more accurate order block placements
// lastHigh:=high>lastHigh?high:lastHigh
// lastLow:=low<lastLow?low:lastLow

// /////////////////////////////////////////////////////// --ORDER BLOCKS-- ////////////////////////////////////////////////////////



// _________________________________________________________________________Plotting_Trend & Bar Colors_________________________________________________________________________

barcolor(trendX > 0 ? color.green : color.red, offset=-1 )
upTrendBarColorInput = input.color (color.green, "Bar Up", inline = "01", group = "Color Settings")
downTrendBarColorInput = input.color (color.red, "Bar Dn", inline = "01", group = "Color Settings")
barColor = trendX == 1 ? upTrendBarColorInput : downTrendBarColorInput
// barcolor(trend == 1 ? upTrendBarColorInput : downTrendBarColorInput, title="Trend Bar Colors")

barcolor(showBarColor ? barColor : na)


plot(showTrendLine ? tsl : na, color = linecolor, style = plot.style_line, linewidth = 1, title = "Trend")
// plot(showBarColor ? barColor : na)

// Plotting_Trend & Bar Colors//

// _________________________________________________________________________Plotting_Scalping_Alerts_____________________________________________________________________________

sellAlert = trendX == -1 and trendX[1] == 1
buyAlert = trendX == 1 and trendX[1] == -1

plotshape(showAlerts ? buyAlert : na, title="Buy Alert", style=shape.triangleup, location=location.belowbar, color=color.green, size=size.tiny, offset=-1)
plotshape(showAlerts ? sellAlert : na, title="Sell Alert", style=shape.triangledown, location=location.abovebar, color=color.red, size=size.tiny, offset=-1)

// alertcondition(buyAlert, title='Buy!!', message='\{"chat_id":"-1001549739381","text":"🟢Buy{{interval}}h\\n#{{ticker}},\\nEnter-{{close}}$\\nStop-{{low}}$"}')
// alertcondition(sellAlert, title='Sell!!', message='\{"chat_id":"-1001549739381","text":"🔴Sell{{interval}}h\\n#{{ticker}},\\nEnter-{{close}}$\\nStop-{{high}}$"}')


plot(tsl, "TSL_Alert", display=display.none)

message_Sell = '\{"chat_id":"-1001549739381","text":"🔴Sell - {{interval}}\\n[#{{ticker}}](https://ru.tradingview.com/chart/?symbol={{exchange}}%3A{{ticker}}),\\nEnter-{{close}}$\\nStop-{{high}}$","parse_mode": "Markdown","disable_web_page_preview": true}'
message_Buy = '\{"chat_id":"-1001549739381","text":"🟢Buy - {{interval}}\\n[#{{ticker}}](https://ru.tradingview.com/chart/?symbol={{exchange}}%3A{{ticker}}),\\nEnter-{{close}}$\\nStop-{{low}}$","parse_mode": "Markdown","disable_web_page_preview": true}'

// message_Sell = '\{"chat_id":"-1001549739381","text":"🔴Sell - {{interval}}\\n[#{{ticker}}](https://ru.tradingview.com/chart/?symbol={{exchange}}%3A{{ticker}}),\\nEnter-{{close}}$\\nStop-{{plot("TSL_Alert")}}$","parse_mode": "Markdown","disable_web_page_preview": true}'
// message_Buy = '\{"chat_id":"-1001549739381","text":"🟢Buy - {{interval}}\\n[#{{ticker}}](https://ru.tradingview.com/chart/?symbol={{exchange}}%3A{{ticker}}),\\nEnter-{{close}}$\\nStop-{{plot("TSL_Alert")}}$","parse_mode": "Markdown","disable_web_page_preview": true}'


alertcondition(sellAlert, title='Sell_Alert_NEW', message=message_Sell)
alertcondition(buyAlert, title='Buy_Alert_NEW', message=message_Buy)




// if trend == 1 and trend[1] == -1 
//     strategy.entry("Buy ", strategy.long)

// if trend == -1 and trend[1] == 1 
//     strategy.entry("Sell ", strategy.short)

// Plotting_Scalping_Alerts//



// //HULL TREND WITH KAHLMAN

srchull         = hl2
lengthhull      = 16
gain            = 7000


hma(_srchull, _lengthhull) =>
    ta.wma((2 * ta.wma(_srchull, _lengthhull / 2)) - ta.wma(_srchull, _lengthhull), math.round(math.sqrt(_lengthhull)))
    
hma3(_srchull, _lengthhull) =>
    p = lengthhull/2
    ta.wma(ta.wma(hl2,p/3)*3 - ta.wma(hl2,p/2) - ta.wma(hl2,p),p)

kahlman(x, g) =>
    kf = 0.0
    dk = x - nz(kf[1], x)
    smooth = nz(kf[1],x)+dk*math.sqrt((g/10000)*2)
    velo = 0.0
    velo := nz(velo[1],0) + ((g/10000)*dk)
    kf := smooth+velo
  
a = kahlman(hma(srchull, lengthhull), gain) 
b = kahlman(hma3(srchull, lengthhull), gain) 
c = b > a ? color.lime : color.red
crossdn = a > b and a[1] < b[1]
crossup = b > a and b[1] < a[1]

// plotshape(showcross and crossdn ? a : na, location=location.abovebar, style=shape.triangledown, color=color.yellow, text="", textcolor=color.white, transp=0, offset=-1)
// plotshape(showcross and crossup ? a : na, location=location.belowbar, style=shape.triangleup, color=color.blue, text="", textcolor=color.white, transp=0, offset=-1)
plotshape(scalpingAlerts and crossdn ? a : na, location=location.abovebar, style=shape.triangledown, color=color.yellow, text="", textcolor=color.white, transp=0, offset=0)
plotshape(scalpingAlerts and crossup ? a : na, location=location.belowbar, style=shape.triangleup, color=color.blue, text="", textcolor=color.white, transp=0, offset=0)



// /////////////////////////////////////////////////////// --DYNAMIC CHANNEL-- ////////////////////////////////////////////////////////

GRP4 = "Dynamic channel"
lengthInput = input.int(200, title="Length", minval = 1, maxval = 5000, inline ="Dynamic channel", group = GRP4)
sourceInput = input.source(hl2, title="Source", inline ="Dynamic channel", group = GRP4)
useUpperDevInput = input.bool(true, title="Deviation", inline = "Deviation", group = GRP4)
upperMultInput = input.float(2.0, title="", inline = "Deviation", group = GRP4)
useLowerDevInput = useUpperDevInput
lowerMultInput = upperMultInput

// group4 = "Display Settings"
extendLeftInput = input.bool(false,  title="Extend Lines Left", inline ="Lines", group = GRP4)
extendRightInput = input.bool(false,  title="Extend Lines Right", inline ="Lines", group = GRP4)
extendStyle = switch
    extendLeftInput and extendRightInput => extend.both
    extendLeftInput => extend.left
    extendRightInput => extend.right
    => extend.none

// group3 = "Color Settings"
colorUpper = input.color(color.new(color.orange, 95), "", inline = "Deviation", group = GRP4)
colorLower = colorUpper 
baseLine = colorUpper


calcSlope(source, length) =>
    max_bars_back(source, 5000)
    if not barstate.islast or length <= 1 or not showChannel
        [float(na), float(na), float(na)]
    else
        sumX = 0.0
        sumY = 0.0
        sumXSqr = 0.0
        sumXY = 0.0
        for i = 0 to length - 1 by 1
            val = source[i]
            per = i + 1.0
            sumX += per
            sumY += val
            sumXSqr += per * per
            sumXY += val * per
        slope = (length * sumXY - sumX * sumY) / (length * sumXSqr - sumX * sumX)
        average = sumY / length
        intercept = average - slope * sumX / length + slope
        [slope, average, intercept]
        
[s, aa, i] = calcSlope(sourceInput, lengthInput)
startPrice = i + s * (lengthInput - 1)
endPrice = i
var line base = na
if na(base) and not na(startPrice)
    base := line.new(bar_index - lengthInput + 1, startPrice, bar_index, endPrice, width=1, extend=extendStyle, color=color.new(baseLine, 0))
else
    line.set_xy1(base, bar_index - lengthInput + 1, startPrice)
    line.set_xy2(base, bar_index, endPrice)
    na
    
calcDev(source, length, slope, average, intercept) =>
    upDev = 0.0
    dnDev = 0.0
    stdDevAcc = 0.0
    dsxx = 0.0
    dsyy = 0.0
    dsxy = 0.0
    periods = length - 1
    daY = intercept + slope * periods / 2
    val = intercept
    for j = 0 to periods by 1
        price = high[j] - val
        if price > upDev
            upDev := price
        price := val - low[j]
        if price > dnDev
            dnDev := price
        price := source[j]
        dxt = price - average
        dyt = val - daY
        price -= val
        stdDevAcc += price * price
        dsxx += dxt * dxt
        dsyy += dyt * dyt
        dsxy += dxt * dyt
        val += slope
    stdDev = math.sqrt(stdDevAcc / (periods == 0 ? 1 : periods))
    [stdDev, upDev, dnDev]
    
[stdDev, upDev, dnDev] = calcDev(sourceInput, lengthInput, s, a, i)
upperStartPrice = startPrice + (useUpperDevInput ? upperMultInput * stdDev : upDev)
upperEndPrice = endPrice + (useUpperDevInput ? upperMultInput * stdDev : upDev)
var line upper = na
lowerStartPrice = startPrice + (useLowerDevInput ? -lowerMultInput * stdDev : -dnDev)
lowerEndPrice = endPrice + (useLowerDevInput ? -lowerMultInput * stdDev : -dnDev)
var line lower = na
if na(upper) and not na(upperStartPrice)
    upper := line.new(bar_index - lengthInput + 1, upperStartPrice, bar_index, upperEndPrice, width=1, extend=extendStyle, color=color.new(colorUpper, 0))
else
    line.set_xy1(upper, bar_index - lengthInput + 1, upperStartPrice)
    line.set_xy2(upper, bar_index, upperEndPrice)
    na
if na(lower) and not na(lowerStartPrice)
    lower := line.new(bar_index - lengthInput + 1, lowerStartPrice, bar_index, lowerEndPrice, width=1, extend=extendStyle, color=color.new(colorLower, 0))
else
    line.set_xy1(lower, bar_index - lengthInput + 1, lowerStartPrice)
    line.set_xy2(lower, bar_index, lowerEndPrice)
    na
    
// linefill.new(showChannel ? upper : na, base, color = colorUpper)
// linefill.new(showChannel ? base : na, lower, color = colorLower)


// /////////////////////////////////////////////////////// --DYNAMIC CHANNEL-- ////////////////////////////////////////////////////////

    
// /////////////////////////////////////////////////////// --CMA LINES-- ////////////////////////////////////////////////////////

//Ploting SMA Lines    
src = input(close, title="Source", group = "SMA Settings")

showLen = input.bool(true, "", group = "SMA Settings", inline = "00")
len = input.int(21, title="Sma1", group = "SMA Settings", inline = "00")
out = ta.sma(src, len)
color = input.color(color.new(color.blue, 0), "", group = "SMA Settings", inline = "00")

showLen2 = input.bool(true, "", group = "SMA Settings", inline = "01")
len2 = input(55, title="Sma2", inline = "01", group = "SMA Settings")
out2 = ta.sma(src, len2)
color2 = input.color(color.new(color.orange, 0), "", group = "SMA Settings", inline = "01")

showLen3 = input.bool(true, "", group = "SMA Settings", inline = "01")
len3 = input(89, title="Sma3", inline = "01", group = "SMA Settings")
out3 = ta.sma(src, len3)
color3 = input.color(color.new(color.maroon, 0), "", group = "SMA Settings", inline = "01")

showLen4 = input.bool(true, "", group = "SMA Settings", inline = "02")
len4 = input(144, title="Sma4", inline = "02", group = "SMA Settings")
out4 = ta.sma(src, len4)
color4 = input.color(color.new(color.green, 0), "", group = "SMA Settings", inline = "02")

showLen5 = input.bool(true, "", group = "SMA Settings", inline = "02")
len5 = input(233, title="Sma5", inline = "02", group = "SMA Settings")
out5 = ta.sma(src, len5)
color5 = input.color(color.new(color.purple, 0), "", group = "SMA Settings", inline = "02")


plot(showLen and showCmaLines ? out : na, color = color, title="Sma1")
plot(showLen2 and showCmaLines ? out2 : na, color = color2, title="Sma2")
plot(showLen3 and showCmaLines ? out3 : na, color = color3, title="Sma3")
plot(showLen4 and showCmaLines ? out4 : na, color = color4, linewidth=1, title="Sma4")
plot(showLen5 and showCmaLines ? out5 : na, color = color5, linewidth=3, title="Sma5")


// /////////////////////////////////////////////////////// --CMA LINES-- ////////////////////////////////////////////////////////





// -------------------------------------------------- Pivots styling options --------------------------------------------------

INP_supportStyle    = input.string(i_line0,
      " ",
      inline = "line8",   group = "Styling Options",
      options = [ i_line0, i_line1, i_line2])
INP_supportColour   = input( color.red," S Levels",inline = "line8",   group = "Styling Options")

INP_pivotStyle      = input.string(i_line0," ",inline = "line9",   group = "Styling Options", options = [ i_line0, i_line1, i_line2])
INP_pivotColour     = input( color.silver,  " P Levels",    inline = "line9",   group = "Styling Options")

INP_resistStyle     = input.string(i_line0,
      " ",       
      inline = "line10",  group = "Styling Options",
      options = [ i_line0, i_line1, i_line2])
INP_resistColour    = input( color.green,     " R Levels",    inline = "line10",  group = "Styling Options")

// -- drawing settings for selection A
array.set(i_settingsA, 0, INP_showPivotsA ? 1 : 0)
array.set(i_settingsA, 1, INP_supportsA)
array.set(i_settingsA, 2, INP_resistsA)
// -- drawing settings for selection B
array.set(i_settingsB, 0, INP_showPivotsB ? 1 : 0)
array.set(i_settingsB, 1, INP_supportsB)
array.set(i_settingsB, 2, INP_resistsB)
// -- drawing settings for selection C
array.set(i_settingsC, 0, INP_showPivotsC ? 1 : 0)
array.set(i_settingsC, 1, INP_supportsC)
array.set(i_settingsC, 2, INP_resistsC)

// -------------------------------------------------- Pivots styling options --------------------------------------------------


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//                          ====== FUNCTIONS ======                           //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

f_getResolution( _inputResolution ) =>
    //  string  _inputResolution : user selected resolution input
    // () Description:
    //  - Resolver for custom resolution input selection, converts input to
    //    compatible return string for security, output is also used for less
    //    verbose label text options.
    // Dependencies:
    //  - i_res1, i_res2, i_res3, i_res4, i_res5, i_res6
    //  - i_res7, i_res8, i_res9, i_res10, i_res11, i_res12
    // Notes:
    //  - i_res0 excluded as it's a token placeholder for default "60".

    string _r       = _inputResolution  // a more ternary challenge friendly var
    string _default = "60"              // if i_res0 was input, or failure.

    // compare input to determine proper string return for security calls.
    _return = _r == i_res1 ? "120"  : _r == i_res2 ? "180"  : _r == i_res3 ? "240"  :
              _r == i_res4 ? "360"  : _r == i_res5 ? "720"  : _r == i_res6 ? "1D"   :
              _r == i_res7 ? "5D"   : _r == i_res8 ? "1W"   : _r == i_res9 ? "1M"   :
              _r == i_res10 ? "3M"  : _r == i_res11 ? "6M"  : _r == i_res12 ? "12M" : _default

f_getLineStyle( _inputStyle ) =>
    //  string  _inputStyle : user selected style input
    // () resolver for custom line style input selection, returns a usable
    //    line style type.
    // Dependencies:
    //  - i_line1, i_line2
    // Notes:
    //  * i_line0 omitted as we default to 'line.style_solid' anyway

    // compare input to determine proper line style to return.
    _return = _inputStyle == i_line1 ? line.style_dotted :
              _inputStyle == i_line2 ? line.style_dashed : line.style_solid

// -- helper function for checking if a value is inside a min-max range
f_isInsideRange(_val, _min, _max) => _val >= _min and _val <= _max

f_getPivotTraditional( _prevHigh, _prevLow, _prevClose ) =>
    //  float   _prevHigh | _prevLow | _prevClose : HTF security OHLC values
    // () calculates a pivot set and assigns to proper array indexes for return.
    // Notes:
    //  - f_renderPivotArray() expects float data in the following sequence..
    //
    //      Pivot     : [ 0 ]
    //      Supports  : [ 1 to i_maxLevels ]
    //      Resists   : [ ( i_maxLevels + 1 ) to i_maxLength ]

    // init empty array with predefined length of i_maxLength
    var float[] _array = array.new_float( i_maxLength, na )

    // pivot level, array index [0]
    _pivot = ( _prevHigh + _prevLow + _prevClose ) / 3
    array.set( _array, 0, _pivot )

    // support levels, array indexes [1] through [i_maxLevels]
    array.set( _array, 1, _pivot * 2.003 - _prevHigh )
    array.set( _array, 2, _pivot - ( _prevHigh - _prevLow ) )
    array.set( _array, 3, _pivot * 2 - ( 2 * _prevHigh - _prevLow ) )
    array.set( _array, 4, _pivot * 3 - ( 3 * _prevHigh - _prevLow ) )
    array.set( _array, 5, _pivot * 4 - ( 4 * _prevHigh - _prevLow ) )

    // resistance levels, array indexes [i_maxLevels + 1] through [i_maxLength]
    array.set( _array, 1 + i_maxLevels, _pivot * 1.997 - _prevLow )
    array.set( _array, 2 + i_maxLevels, _pivot + ( _prevHigh - _prevLow ) )
    array.set( _array, 3 + i_maxLevels, _pivot * 2 + ( _prevHigh - 2 * _prevLow ) )
    array.set( _array, 4 + i_maxLevels, _pivot * 3 + ( _prevHigh - 3 * _prevLow ) )
    array.set( _array, 5 + i_maxLevels, _pivot * 4 + ( _prevHigh - 4 * _prevLow ) )

    _return = _array


f_getPivotSet( _flavour, _resolution ) =>
    //  string  _flavour    : user input pivot type selection
    //  string  _resolution : user input resolution selection
    // () gets OHLC values from selected resolution, and returns requested
    //    pivot calculation array.

    // previous OHLC series for selected resolution
    [ _prevOpen,
      _prevHigh,
      _prevLow,
      _prevClose ] =  request.security( syminfo.tickerid, _resolution, [ open[1], high[1], low[1], close[1] ], lookahead = barmerge.lookahead_on )
    
    var float _currOpen = na
    if ta.change( time( _resolution ) ) != 0
        _currOpen := open

    // float array to contain S|R levels for return.
    var float[] _pivotSet = array.new_float(i_maxLength, na)

    _pivotSet := _flavour == i_piv0? f_getPivotTraditional( _prevHigh, _prevLow, _prevClose ) : na

    _pivotSet // return the float array

f_renderPivotArray( _resolution, _settings, _floats, _lines, _labels ) =>
    //  string  _resolution : user selected resolution input
    //  int[]   _settings   : pivot specific input settings
    //  float[] _floats     : pivot float array
    //  line[]  _lines      : line array to hold rendered lines
    //  label[] _labels     : label array to hold rendered labels
    //  
    // () Description:
    //  - Designed for scalability and plug-n-play functionality if any new
    //    pivot type is added, or extended.
    //  - If a f_pivotType() function properly assigns it's float values in the
    //    following format/order, it should be able to to render them with no
    //    hassle at all.
    //
    //      Pivot     : [ 0 ]
    //      Supports  : [ 1 to i_maxLevels ]
    //      Resists   : [ ( i_maxLevels + 1 ) to i_maxLength ]  

    // set up a few common vars for drawing using 'time' placement
    _xloc   = xloc.bar_time
    _x1     = ta.valuewhen( ta.change( time( _resolution ) ), time, 0 ) // time
    _x2     = time_close( _resolution ) // new! Thanks pine team <3

    // set up some temp vars for creating our lines and labels
    var line    _line       = na
    var label   _labelLeft  = na
    var label   _labelRight = na
    var label   _labelPrice = na

    // init some readable settings variables to hold _settings data
    var bool    _showPivot      = false
    var int     _maxSupports    = i_maxLevels
    var int     _maxResists     = i_maxLevels

    // hand off the settings array to the vars
    _showPivot      := array.get( _settings, 0 ) > 0 ? true : false
    _maxSupports    := array.get( _settings, 1 )
    _maxResists     := array.get( _settings, 2 )

    // if we want to show the particular pivot set
    // * the change() check was causing issues on extended hours intraday charts
    //   so i have removed it for now. I will look into other options for the
    //   next proper update.
    if _showPivot and showPivots // change ( time( _resolution ) ) != 0 and _showPivot
    
        // clean up old lines and labels before drawing our new set
        for i = 1 to array.size( _lines ) // loop and delete 1 by 1
            line.delete( array.get( _lines, i - 1 ) )

        // the label array is dynamic length, so we..
        if array.size( _labels ) > 0 // ..check to see if it has content..
            for i = 1 to array.size( _labels ) // ..then loop it into the trash
                label.delete( array.shift( _labels ) )

        // check for properly populated float array
        if array.size( _floats ) > 0 and not na( array.get( _floats, 0 ) )

            // now loop through the floats
            for i = 1 to array.size( _floats )

                // don't want to bother with [i - 1] throughout the entire loop
                _index = i - 1 // so set up a var

                // if we have a valid float at the current loop index
                if not na( array.get( _floats, _index ) )

                    // common variables used in all conditions
                    _activePrice = array.get( _floats, _index )
                    _priceString = str.tostring( _activePrice, "#.######" )

                    //  IDENTIFYING SUPPORT LEVELS IN ARRAY
                    //
                    // support index range : [ from 1 to i_maxLevels ]
                    if f_isInsideRange( _index, 1, i_maxLevels )

                        // only draw levels : [ from 1 to _maxSupports ]
                        if f_isInsideRange( _index, 1, _maxSupports )

                            // dynamic line width based on index value
                            int     _width  = _index > 3 ? _index - 2 : _index
                            // use index to set level numbers on labels
                            string  _level  = str.tostring( _index )

                            _line   := line.new( _x1, _activePrice, _x2, _activePrice, _xloc, extend.none,
                                                      style = f_getLineStyle( INP_supportStyle ),
                                                      color = INP_supportColour,
                                                      width = _width )

                            // _labelLeft  := label.new( _x1, _activePrice, "S" + _level + "\n", _xloc,
                            //                           style = label.style_label_left,
                            //                           color = #00000000,
                            //                           textcolor = INP_supportColour )

                            _labelRight := label.new( _x2, _activePrice, "S" + _level + "\t" + _priceString, _xloc,
                                                      style = label.style_label_left,
                                                      color = #00000000,
                                                      textcolor = INP_supportColour )

                            // _labelPrice := INP_showPrice ? label.new( _x2, _activePrice, _priceString, _xloc,
                            //                           style = label.style_label_left,
                            //                           color = #00000000,
                            //                           textcolor = INP_priceColour ) : na

                    //  IDENTIFYING RESISTANCE LEVELS IN ARRAY
                    //
                    // resistance index range : [ from (1 + i_maxLevels) to (2 * i_maxLevels) ]
                    else if f_isInsideRange( _index, 1 + i_maxLevels, 2 * i_maxLevels )

                        // only draw levels : [ from (1 + i_maxLevels) to (_maxResists + i_maxLevels) ]
                        if f_isInsideRange( _index, 1 + i_maxLevels, _maxResists + i_maxLevels )

                            // adjusted _index value to attain 1/2/3 sequence for string operation
                            int     _adjust = _index - i_maxLevels
                            // dynamic line width based on adjusted _index value
                            int     _width  = _adjust > 3 ? _adjust - 2 : _adjust
                            // use adjusted index value to set proper level numbers on labels
                            string  _level  = str.tostring( _adjust )

                            _line   := line.new( _x1, _activePrice, _x2, _activePrice, _xloc, extend.none,
                                                      style = f_getLineStyle( INP_resistStyle ),
                                                      color = INP_resistColour,
                                                      width = _width )

                            // _labelRight  := label.new( _x2, _activePrice, "R" + _level + "\t" + _priceString, _xloc,
                            //                           style = label.style_none,
                            //                           color = #00000000,
                            //                           textcolor = INP_resistColour )

                            _labelRight := label.new( _x2, _activePrice, "R" + _level + "\t" + _priceString, _xloc,
                                                      style = label.style_label_left,
                                                      color = #00000000,
                                                      textcolor = INP_resistColour )

                            // _labelPrice := INP_showPrice ? label.new( _x2, _activePrice, _priceString, _xloc,
                            //                           style = label.style_label_left,
                            //                           color = #00000000,
                            //                           textcolor = INP_priceColour ) : na

                    else // PIVOT - No identification needed, always using index 0

                        _line   := line.new( _x1, _activePrice, _x2, _activePrice, _xloc, extend.none,
                                                  style = f_getLineStyle( INP_pivotStyle ),
                                                  color = INP_pivotColour,
                                                  width = 3 )

                        // _labelLeft  := label.new( _x1, _activePrice, "PP\n", _xloc,
                        //                           style = label.style_label_left,
                        //                           color = #00000000,
                        //                           textcolor = INP_pivotColour )

                        _labelRight  := label.new( _x2, _activePrice, "PP\t" + _priceString, _xloc,
                                                  style = label.style_label_left,
                                                  color = #00000000,
                                                  textcolor = INP_pivotColour )
                                                  
                        // _labelRight  := label.new( _x2, _activePrice, "\n" + "\n" + _priceString, _xloc, style =  label.style_none,color = #00000000,textcolor = INP_priceColour )
                                                  
                        // _labelPrice := INP_showPrice ? label.new( _x2, _activePrice, _priceString, _xloc,
                        //                           style = label.style_label_left,
                        //                           color = #00000000,
                        //                           textcolor = INP_priceColour ) : na

                    // set our line to it's respective array index
                    array.set( _lines, _index, _line )

                    // push labels into array, order doesn't matter.
                    if not na(_labelLeft)
                        array.push( _labels, _labelLeft )
                    if not na(_labelRight)
                        array.push( _labels, _labelRight )
                    if not na(_labelPrice)
                        array.push( _labels, _labelPrice )

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//                   ====== SERIES, LINES and LABELS ======                   //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

// -- selected resolutions
string _resolutionA = f_getResolution( INP_resolutionA )
string _resolutionB = f_getResolution( INP_resolutionB )
string _resolutionC = f_getResolution( INP_resolutionC )

// -- pivot series price data sets
float[] _pivotFloatsA   = f_getPivotSet( INP_flavourA, _resolutionA )
float[] _pivotFloatsB   = f_getPivotSet( INP_flavourB, _resolutionB )
float[] _pivotFloatsC   = f_getPivotSet( INP_flavourC, _resolutionC )

// -- pivot lines array A, and companion labels array
var line[]  _pivotLinesA    = array.new_line( i_maxLength, na )
var label[] _pivotLabelsA   = array.new_label()

// -- pivot lines array B, and companion labels array
var line[]  _pivotLinesB    = array.new_line( i_maxLength, na )
var label[] _pivotLabelsB   = array.new_label()

// -- pivot lines array C, and companion labels array
var line[]  _pivotLinesC    = array.new_line( i_maxLength, na )
var label[] _pivotLabelsC   = array.new_label()

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//                     ====== DRAWING and PLOTTING ======                     //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

// -- feed in our settings and data to the render function for set A
f_renderPivotArray( _resolutionA, i_settingsA, _pivotFloatsA, _pivotLinesA, _pivotLabelsA )

// -- feed in our settings and data to the render function for set B
f_renderPivotArray( _resolutionB, i_settingsB, _pivotFloatsB, _pivotLinesB, _pivotLabelsB )

// -- feed in our settings and data to the render function for set C
f_renderPivotArray( _resolutionC, i_settingsC, _pivotFloatsC, _pivotLinesC, _pivotLabelsC )

// ====== DRAWING and PLOTTING ======   



// ------------- zigzag -------------//
tooltip_zigzag      = 'The Zig Zag indicator is used to identify price trends then connected by straight lines that help the trader visual the price action' + 
                      'This indicator works to eliminate confusion over small price changes or fluctuations and aims to project trend changes overtime'


group_zigzag = 'Waves Settings'

// i_zigZag     = input.bool(true, 'Zig Zag  ', inline='ZZ', group=group_zigzag, tooltip=tooltip_zigzag)
i_zzColor    = input.color(#ffffff, 'Color ', inline='ZZ', group=group_zigzag)
i_zzStyle    = input.string('Dotted', 'Style ', options=['Dashed', 'Dotted', 'Solid'], inline='ZZ', group=group_zigzag)
i_zzWidth    = input.int(1, 'Width', minval=1, inline='ZZ', group=group_zigzag)


// ---------------------------------------------------------------------------------------------- //
// -Calculations -------------------------------------------------------------------------------- //
i_dev_thresh = ta.atr(10) / close * 100 * input.float(3, 'Deviation', minval=0, inline='ZZz', group=group_zigzag)
i_depth      = input.int(11, 'Depth', minval=1, inline='ZZz', group=group_zigzag)


var line lineLast = na
var int iLast = 0
var int iPrev = 0
var float pLast = 0
var isHighLast = false  // otherwise the last pivot is a low pivot

var iPrevPivot = 0
var pPrevPivot = 0.
var iLastPivot = 0
var pLastPivot = 0.

pivots(src, length, isHigh) =>
    l2 = length * 2
    c = nz(src[length])
    ok = true

    for i = 0 to l2 by 1
        if isHigh and src[i] > c
            ok := false
            ok

        if not isHigh and src[i] < c
            ok := false
            ok
    if ok
        [bar_index[length], c]
    else
        [int(na), float(na)]

[iH, pH] = pivots(high, i_depth / 2, true)
[iL, pL] = pivots(low, i_depth / 2, false)

calc_dev(base_price, price) =>
    100 * (price - base_price) / price

pivotFound(dev, isHigh, index, price) =>
    if isHighLast == isHigh and not na(lineLast)
        // same direction
        if isHighLast ? price > pLast : price < pLast
            line.set_xy2(lineLast, index, price)
            [lineLast, isHighLast]
        else
            [line(na), bool(na)]
    else
        // reverse the direction (or create the very first line)
        if math.abs(dev) > i_dev_thresh
            // price move is significant

            // ---------------------------------------------------------------------------------------- //
            [zzCol, zzWid, zzSty] = if not i_zigZag
                [na, 1, line.style_dashed]
            else
                [i_zzColor, i_zzWidth, i_zzStyle == 'Solid' ? line.style_solid : i_zzStyle == 'Dotted' ? line.style_dotted : line.style_dashed]
            // ---------------------------------------------------------------------------------------- //

            id = line.new(iLast, pLast, index, price, color=zzCol, width=zzWid, style=zzSty)
            [id, isHigh]
        else
            [line(na), bool(na)]

if not na(iH)
    dev = calc_dev(pLast, pH)
    [id, isHigh] = pivotFound(dev, true, iH, pH)

    if not na(id)
        if id != lineLast
            // ---------------------------------------------------------------------------------------- //
            iPrevPivot := line.get_x1(lineLast)
            pPrevPivot := line.get_y1(lineLast)
            iLastPivot := line.get_x2(lineLast)
            pLastPivot := line.get_y2(lineLast)

            if not i_zigZag
            // ---------------------------------------------------------------------------------------- //

                line.delete(lineLast)

        lineLast := id
        isHighLast := isHigh
        iPrev := iLast
        iLast := iH
        pLast := pH
        pLast
else
    if not na(iL)
        dev = calc_dev(pLast, pL)
        [id, isHigh] = pivotFound(dev, false, iL, pL)

        if not na(id)
            if id != lineLast
                // ---------------------------------------------------------------------------------------- //
                iPrevPivot := line.get_x1(lineLast)
                pPrevPivot := line.get_y1(lineLast)
                iLastPivot := line.get_x2(lineLast)
                pLastPivot := line.get_y2(lineLast)

                if not i_zigZag
                // ---------------------------------------------------------------------------------------- //

                    line.delete(lineLast)

            lineLast := id
            isHighLast := isHigh
            iPrev := iLast
            iLast := iL
            pLast := pL
            pLast




// ------------------------------------ zigzag ------------------------------------------------------------

//----------------FFPivots--------------//
dp          =   input(true,         title="Show Daily     Future Pivot")
wp          =   input(true,         title="Show Weekly    Future Pivot")
mp          =   input(true,         title="Show Monthly   Future Pivot")

srv         =   input(true,         title="S1 R1 Visible")
LblBR       =   input(#00000000,    title='Label Backround')
txtColor    =   input(color.black,  title='Label Textcolor')

clr         =   input(#D47928,      title='Pivot Color')
clyp        =   input(color.blue,   title='Yearly Pivot Color')
_LineStyle  = input.string('Dotted', 'Style ', options=['Dashed', 'Dotted', 'Solid'])

daily_high  =   request.security(syminfo.tickerid, "D", high,   lookahead=barmerge.lookahead_on)
daily_low   =   request.security(syminfo.tickerid, "D", low,    lookahead=barmerge.lookahead_on)

weekly_high =   request.security(syminfo.tickerid, "W", high,   lookahead=barmerge.lookahead_on)
weekly_low  =   request.security(syminfo.tickerid, "W", low,    lookahead=barmerge.lookahead_on)

monthly_high=   request.security(syminfo.tickerid, "M", high,   lookahead=barmerge.lookahead_on)
monthly_low =   request.security(syminfo.tickerid, "M", low,    lookahead=barmerge.lookahead_on)

var float yearly_high = high
var float yearly_low = low
newmonth = ta.change(time('M')) != 0
if month == 1 and newmonth
    yearly_high := high
    yearly_low := low
else    
    yearly_high := math.max(high, yearly_high)
    yearly_low := math.min(low, yearly_low)

FPP = (daily_high   + daily_low     + close) / 3
FPw = (weekly_high  + weekly_low    + close) / 3
FPm = (monthly_high + monthly_low   + close) / 3
FPy = (yearly_high  + yearly_low    + close) / 3

DR1 = 2 * FPP - daily_low
DS1 = 2 * FPP - daily_high

WR1 = 2 * FPw - weekly_low
WS1 = 2 * FPw - weekly_high

MR1 = 2 * FPm - monthly_low
MS1 = 2 * FPm - monthly_high

YR1 = 2 * FPy - yearly_low
YS1 = 2 * FPy - yearly_high    


//dt = time - time[1]
dyt     =   request.security(syminfo.tickerid, "D", time_close )
dtt      =  request.security(syminfo.tickerid, "D", time_close ) + request.security(syminfo.tickerid, "D", time) - request.security(syminfo.tickerid, "D", time[1])

wyt     =   request.security(syminfo.tickerid, "W", time_close )
wtt      =  request.security(syminfo.tickerid, "W", time_close ) + request.security(syminfo.tickerid, "W", time) - request.security(syminfo.tickerid, "W", time[1])

myt     =   request.security(syminfo.tickerid, "M", time_close )
mtt      =  request.security(syminfo.tickerid, "M", time_close ) + request.security(syminfo.tickerid, "M", time) - request.security(syminfo.tickerid, "M", time[1])


if barstate.islast
    if dp and (timeframe.isintraday)
        ldpp      =   line.new    (x1 = dyt , y1 = FPP  , x2 = dtt , y2 = FPP, xloc = xloc.bar_time, extend=extend.none,   color   =   clr, style = line.style_dotted,    width   =   2)
        line.delete(ldpp[1])
        lbldpp  =   label.new   (x = dtt , y = FPP, text = "PPD" , xloc = xloc.bar_time, color   =   LblBR,    style   =   label.style_label_left)
        label.delete(lbldpp[1])
        if  srv
            lds1p      =   line.new    (x1 = dyt , y1  =   DS1  , x2 = dtt , y2    =   DS1,     xloc = xloc.bar_time, extend=extend.none,   color   =   clr, style = line.style_dotted)
            line.delete(lds1p[1])
            lblds1p  =   label.new   (x = dtt , y = DS1, text = "S1D" , xloc = xloc.bar_time, color   =   LblBR,    style   =   label.style_label_left)
            label.delete(lblds1p[1])
            ldr1p      =   line.new    (x1 = dyt , y1  =   DR1  , x2 = dtt , y2    =   DR1, xloc = xloc.bar_time, extend=extend.none,   color   =   clr, style = line.style_dotted)
            line.delete(ldr1p[1])
            lbldr1p  =   label.new   (x = dtt , y = DR1, text = "R1D" , xloc = xloc.bar_time, color   =   LblBR,    style   =   label.style_label_left)
            label.delete(lbldr1p[1])
            
    if wp   and (timeframe.isintraday or timeframe.isdaily)
        lwpp      =   line.new    (x1 = wyt , y1  =   FPw  , x2 = wtt , y2          =   FPw,    xloc = xloc.bar_time, extend=extend.none,   color   =   clr,    width   =   3)
        line.delete(lwpp[1])
        lblwpp  =   label.new   (x = wtt , y = FPw, text = "PPW" ,                              xloc = xloc.bar_time,                       color   =   LblBR,    style   =   label.style_label_left)
        label.delete(lblwpp[1])
        if  srv
            lws1p      =   line.new    (x1 = wyt , y1  =   WS1  , x2 = wtt , y2    =   WS1,     xloc = xloc.bar_time, extend=extend.none,   color   =   clr)
            line.delete(lws1p[1])
            lblws1p  =   label.new   (x = wtt , y = WS1, text = "S1W" ,                         xloc = xloc.bar_time,                       color   =   LblBR,    style   =   label.style_label_left)
            label.delete(lblws1p[1])
            lwr1p      =   line.new    (x1 = wyt , y1  =   WR1  , x2 = wtt , y2    =   WR1,     xloc = xloc.bar_time, extend=extend.none,   color   =   clr)
            line.delete(lwr1p[1])
            lblwr1p  =   label.new   (x = wtt , y = WR1, text = "R1W" ,                         xloc = xloc.bar_time,                       color   =   LblBR,    style   =   label.style_label_left)
            label.delete(lblwr1p[1])
    if mp   and (timeframe.isintraday or timeframe.isdaily or timeframe.isweekly)
        lmpp      =   line.new    (x1 = myt , y1  =   FPm  , x2 = mtt , y2          =   FPm,    xloc = xloc.bar_time, extend=extend.none,   color   =   clr,    width   =   3)
        line.delete(lmpp[1])
        lblmpp  =   label.new   (x = mtt , y = FPm, text = "PPM" ,                              xloc = xloc.bar_time,                       color   =   LblBR,    style   =   label.style_label_left)
        label.delete(lblmpp[1])
        if  srv
            lms1p      =   line.new    (x1 = myt , y1  =   MS1  , x2 = mtt , y2    =   MS1,     xloc = xloc.bar_time, extend=extend.none,   color   =   clr)
            line.delete(lms1p[1])
            lblms1p  =   label.new   (x = mtt , y = MS1, text = "S1M" ,                         xloc = xloc.bar_time,                       color   =   LblBR,    style   =   label.style_label_left)
            label.delete(lblms1p[1])
            lmr1p      =   line.new    (x1 = myt , y1  =   MR1  , x2 = mtt , y2    =   MR1,     xloc = xloc.bar_time, extend=extend.none,   color   =   clr)
            line.delete(lmr1p[1])
            lblmr1p  =   label.new   (x = mtt , y = MR1, text = "R1M" ,                         xloc = xloc.bar_time,                       color   =   LblBR,    style   =   label.style_label_left)
            label.delete(lblmr1p[1])
    if month == 12
        lypp      =   line.new    (x1 = myt , y1  =   FPy  , x2 = mtt , y2          =   FPy,    xloc = xloc.bar_time, extend=extend.none,   color   =   clyp,    width   =   3)
        line.delete(lypp[1])
        lblypp  =   label.new   (x = mtt , y = FPy, text = "PPY" ,                              xloc = xloc.bar_time,                       color   =   LblBR,    style   =   label.style_label_left)
        label.delete(lblypp[1])
        if  srv
            lys1p      =   line.new    (x1 = myt , y1  =   YS1  , x2 = mtt , y2    =   YS1,     xloc = xloc.bar_time, extend=extend.none,   color   =   clyp)
            line.delete(lys1p[1])
            lblys1p  =   label.new   (x = mtt , y = YS1, text = "S1Y" ,                         xloc = xloc.bar_time,                       color   =   LblBR,    style   =   label.style_label_left)
            label.delete(lblys1p[1])
            lyr1p      =   line.new    (x1 = myt , y1  =   YR1  , x2 = mtt , y2    =   YR1,     xloc = xloc.bar_time, extend=extend.none,   color   =   clyp)
            line.delete(lyr1p[1])
            lblyr1p  =   label.new   (x = mtt , y = YR1, text = "R1Y" ,                         xloc = xloc.bar_time,                       color   =   LblBR,    style   =   label.style_label_left)
            label.delete(lblyr1p[1])


color TRANSP_CSS = #ffffff00

//Tooltips
string MODE_TOOLTIP          = 'Allows to display historical Structure or only the recent ones'
string STYLE_TOOLTIP         = 'Indicator color theme'
string COLOR_CANDLES_TOOLTIP = 'Display additional candles with a color reflecting the current trend detected by structure'
string SHOW_INTERNAL         = 'Display internal market structure'
string CONFLUENCE_FILTER     = 'Filter non significant internal structure breakouts'
string SHOW_SWING            = 'Display swing market Structure'
string SHOW_SWING_POINTS     = 'Display swing point as labels on the chart'
string SHOW_SWHL_POINTS      = 'Highlight most recent strong and weak high/low points on the chart'
string INTERNAL_OB           = 'Display internal order blocks on the chart\n\nNumber of internal order blocks to display on the chart'
string SWING_OB              = 'Display swing order blocks on the chart\n\nNumber of internal swing blocks to display on the chart'
string FILTER_OB             = 'Method used to filter out volatile order blocks \n\nIt is recommended to use the cumulative mean range method when a low amount of data is available'
string SHOW_EQHL             = 'Display equal highs and equal lows on the chart'
string EQHL_BARS             = 'Number of bars used to confirm equal highs and equal lows'
string EQHL_THRESHOLD        = 'Sensitivity threshold in a range (0, 1) used for the detection of equal highs & lows\n\nLower values will return fewer but more pertinent results'
string SHOW_FVG              = 'Display fair values gaps on the chart'
string AUTO_FVG              = 'Filter out non significant fair value gaps'
string FVG_TF                = 'Fair value gaps timeframe'
string EXTEND_FVG            = 'Determine how many bars to extend the Fair Value Gap boxes on chart'
string PED_ZONES             = 'Display premium, discount, and equilibrium zones on chart'

//-----------------------------------------------------------------------------{
//Settings
//-----------------------------------------------------------------------------{
//General
//----------------------------------------{
mode = input.string('Historical'
  , options = ['Historical', 'Present']
  , group = 'Smart Money Concepts'
  , tooltip = MODE_TOOLTIP)

style = input.string('Colored'
  , options = ['Colored', 'Monochrome']
  , group = 'Smart Money Concepts'
  , tooltip = STYLE_TOOLTIP)

show_trend = input(false, 'Color Candles'
  , group = 'Smart Money Concepts'
  , tooltip = COLOR_CANDLES_TOOLTIP)

//----------------------------------------}
//Internal Structure
//----------------------------------------{
show_internals = input(true, 'Show Internal Structure'
  , group = 'Real Time Internal Structure'
  , tooltip = SHOW_INTERNAL)

show_ibull = input.string('All', 'Bullish Structure'
  , options = ['All', 'BOS', 'CHoCH']
  , inline = 'ibull'
  , group = 'Real Time Internal Structure')

swing_ibull_css = input(#089981, ''
  , inline = 'ibull'
  , group = 'Real Time Internal Structure')

//Bear Structure
show_ibear = input.string('All', 'Bearish Structure'
  , options = ['All', 'BOS', 'CHoCH']
  , inline = 'ibear'
  , group = 'Real Time Internal Structure')

swing_ibear_css = input(#f23645, ''
  , inline = 'ibear'
  , group = 'Real Time Internal Structure')

ifilter_confluence = input(false, 'Confluence Filter'
  , group = 'Real Time Internal Structure'
  , tooltip = CONFLUENCE_FILTER)

internal_structure_size = input.string('Tiny', 'Internal Label Size'
  , options = ['Tiny', 'Small', 'Normal']
  , group = 'Real Time Internal Structure')

//----------------------------------------}
//Swing Structure
//----------------------------------------{
show_Structure = input(true, 'Show Swing Structure'
  , group = 'Real Time Swing Structure'
  , tooltip = SHOW_SWING)

//Bull Structure
show_bull = input.string('All', 'Bullish Structure'
  , options = ['All', 'BOS', 'CHoCH']
  , inline = 'bull'
  , group = 'Real Time Swing Structure')

swing_bull_css = input(#089981, ''
  , inline = 'bull'
  , group = 'Real Time Swing Structure')

//Bear Structure
show_bear = input.string('All', 'Bearish Structure'
  , options = ['All', 'BOS', 'CHoCH']
  , inline = 'bear'
  , group = 'Real Time Swing Structure')

swing_bear_css = input(#f23645, ''
  , inline = 'bear'
  , group = 'Real Time Swing Structure')

swing_structure_size = input.string('Small', 'Swing Label Size'
  , options = ['Tiny', 'Small', 'Normal']
  , group = 'Real Time Swing Structure')

//Swings
show_swings = input(false, 'Show Swings Points'
  , inline = 'swings'
  , group = 'Real Time Swing Structure'
  , tooltip = SHOW_SWING_POINTS)

length = input.int(50, ''
  , minval = 10
  , inline = 'swings'
  , group = 'Real Time Swing Structure')

show_hl_swings = input(true, 'Show Strong/Weak High/Low'
  , group = 'Real Time Swing Structure'
  , tooltip = SHOW_SWHL_POINTS)

//----------------------------------------}
//Order Blocks
//----------------------------------------{
show_iob = input(true, 'Internal Order Blocks'
  , inline = 'iob'
  , group = 'Order Blocks'
  , tooltip = INTERNAL_OB)

iob_showlast = input.int(5, ''
  , minval = 1
  , inline = 'iob'
  , group = 'Order Blocks')

show_ob = input(true, 'Swing Order Blocks'
  , inline = 'ob'
  , group = 'Order Blocks'
  , tooltip = SWING_OB)

ob_showlast = input.int(5, ''
  , minval = 1
  , inline = 'ob'
  , group = 'Order Blocks')

ob_filter = input.string('Atr', 'Order Block Filter'
  , options = ['Atr', 'Cumulative Mean Range']
  , group = 'Order Blocks'
  , tooltip = FILTER_OB)

ibull_ob_css = input.color(color.new(#3179f5, 80), 'Internal Bullish OB'
  , group = 'Order Blocks')

ibear_ob_css = input.color(color.new(#f77c80, 80), 'Internal Bearish OB'
  , group = 'Order Blocks')

bull_ob_css = input.color(color.new(#1848cc, 40), 'Bullish OB'
  , group = 'Order Blocks')

bear_ob_css = input.color(color.new(#b22833, 40), 'Bearish OB'
  , group = 'Order Blocks')

//----------------------------------------}
//EQH/EQL
//----------------------------------------{
show_eq = input(true, 'Equal High/Low'
  , group = 'EQH/EQL'
  , tooltip = SHOW_EQHL)

eq_len = input.int(3, 'Bars Confirmation'
  , minval = 1
  , group = 'EQH/EQL'
  , tooltip = EQHL_BARS)

eq_threshold = input.float(0.1, 'Threshold'
  , minval = 0
  , maxval = 0.5
  , step = 0.1
  , group = 'EQH/EQL'
  , tooltip = EQHL_THRESHOLD)

eq_size = input.string('Tiny', 'Label Size'
  , options = ['Tiny', 'Small', 'Normal']
  , group = 'EQH/EQL')

//----------------------------------------}
//Fair Value Gaps
//----------------------------------------{
show_fvg = input(true, 'Fair Value Gaps'
  , group = 'Fair Value Gaps'
  , tooltip = SHOW_FVG)
  
fvg_auto = input(true, "Auto Threshold"
  , group = 'Fair Value Gaps'
  , tooltip = AUTO_FVG)

fvg_tf = input.timeframe('', "Timeframe"
  , group = 'Fair Value Gaps'
  , tooltip = FVG_TF)

bull_fvg_css = input.color(color.new(#00ff68, 70), 'Bullish FVG'
  , group = 'Fair Value Gaps')

bear_fvg_css = input.color(color.new(#ff0008, 70), 'Bearish FVG'
  , group = 'Fair Value Gaps')

fvg_extend = input.int(20, "Extend FVG"
  , minval = 0
  , group = 'Fair Value Gaps'
  , tooltip = EXTEND_FVG)

//----------------------------------------}
//Previous day/week high/low
//----------------------------------------{
//Daily
show_pdhl = input(false, 'Daily'
  , inline = 'daily'
  , group = 'Highs & Lows MTF')

pdhl_style = input.string('⎯⎯⎯', ''
  , options = ['⎯⎯⎯', '----', '····']
  , inline = 'daily'
  , group = 'Highs & Lows MTF')

pdhl_css = input(#2157f3, ''
  , inline = 'daily'
  , group = 'Highs & Lows MTF')

//Weekly
show_pwhl = input(false, 'Weekly'
  , inline = 'weekly'
  , group = 'Highs & Lows MTF')

pwhl_style = input.string('⎯⎯⎯', ''
  , options = ['⎯⎯⎯', '----', '····']
  , inline = 'weekly'
  , group = 'Highs & Lows MTF')

pwhl_css = input(#2157f3, ''
  , inline = 'weekly'
  , group = 'Highs & Lows MTF')

//Monthly
show_pmhl = input(false, 'Monthly'
  , inline = 'monthly'
  , group = 'Highs & Lows MTF')

pmhl_style = input.string('⎯⎯⎯', ''
  , options = ['⎯⎯⎯', '----', '····']
  , inline = 'monthly'
  , group = 'Highs & Lows MTF')

pmhl_css = input(#2157f3, ''
  , inline = 'monthly'
  , group = 'Highs & Lows MTF')

//----------------------------------------}
//Premium/Discount zones
//----------------------------------------{
show_sd = input(false, 'Premium/Discount Zones'
  , group = 'Premium & Discount Zones'
  , tooltip = PED_ZONES)

premium_css = input.color(#f23645, 'Premium Zone'
  , group = 'Premium & Discount Zones')

eq_css = input.color(#b2b5be, 'Equilibrium Zone'
  , group = 'Premium & Discount Zones')

discount_css = input.color(#089981, 'Discount Zone'
  , group = 'Premium & Discount Zones')

//-----------------------------------------------------------------------------}
//Functions
//-----------------------------------------------------------------------------{
n = bar_index

atr = ta.atr(200)
cmean_range = ta.cum(high - low) / n

//HL Output function
hl() => [high, low]

//Get ohlc values function
get_ohlc()=> [close[1], open[1], high, low, high[2], low[2]]

//Display Structure function
display_Structure(x, y, txt, css, dashed, down, lbl_size)=>
    structure_line = line.new(x, y, n, y
      , color = css
      , style = dashed ? line.style_dashed : line.style_solid)

    structure_lbl = label.new(int(math.avg(x, n)), y, txt
      , color = TRANSP_CSS
      , textcolor = css
      , style = down ? label.style_label_down : label.style_label_up
      , size = lbl_size)

    if mode == 'Present'
        line.delete(structure_line[1])
        label.delete(structure_lbl[1])

//Swings detection/measurements
swings(len)=>
    var os = 0
    
    upper = ta.highest(len)
    lower = ta.lowest(len)

    os := high[len] > upper ? 0 : low[len] < lower ? 1 : os[1]

    top = os == 0 and os[1] != 0 ? high[len] : 0
    btm = os == 1 and os[1] != 1 ? low[len] : 0

    [top, btm]

//Order block coordinates function
ob_coord(use_max, loc, target_top, target_btm, target_left, target_type)=>
    min = 99999999.
    max = 0.
    idx = 1

    ob_threshold = ob_filter == 'Atr' ? atr : cmean_range 

    //Search for highest/lowest high within the structure interval and get range
    if use_max
        for i = 1 to (n - loc)-1
            if (high[i] - low[i]) < ob_threshold[i] * 2
                max := math.max(high[i], max)
                min := max == high[i] ? low[i] : min
                idx := max == high[i] ? i : idx
    else
        for i = 1 to (n - loc)-1
            if (high[i] - low[i]) < ob_threshold[i] * 2
                min := math.min(low[i], min)
                max := min == low[i] ? high[i] : max
                idx := min == low[i] ? i : idx

    array.unshift(target_top, max)
    array.unshift(target_btm, min)
    array.unshift(target_left, time[idx])
    array.unshift(target_type, use_max ? -1 : 1)

//Set order blocks
display_ob(boxes, target_top, target_btm, target_left, target_type, show_last, swing, size)=>
    for i = 0 to math.min(show_last-1, size-1)
        get_box = array.get(boxes, i)

        box.set_lefttop(get_box, array.get(target_left, i), array.get(target_top, i))
        box.set_rightbottom(get_box, array.get(target_left, i), array.get(target_btm, i))
        box.set_extend(get_box, extend.right)

        color css = na
        
        if swing 
            if style == 'Monochrome'
                css := array.get(target_type, i) == 1 ? color.new(#b2b5be, 80) : color.new(#5d606b, 80)
                border_css = array.get(target_type, i) == 1 ? #b2b5be : #5d606b
                box.set_border_color(get_box, border_css)
            else
                css := array.get(target_type, i) == 1 ? bull_ob_css : bear_ob_css
                box.set_border_color(get_box, css)

            box.set_bgcolor(get_box, css)
        else
            if style == 'Monochrome'
                css := array.get(target_type, i) == 1 ? color.new(#b2b5be, 80) : color.new(#5d606b, 80)
            else
                css := array.get(target_type, i) == 1 ? ibull_ob_css : ibear_ob_css
            
            box.set_border_color(get_box, css)
            box.set_bgcolor(get_box, css)
        
//Line Style function
get_line_style(style) =>
    out = switch style
        '⎯⎯⎯'  => line.style_solid
        '----' => line.style_dashed
        '····' => line.style_dotted

//Set line/labels function for previous high/lows
phl(h, l, tf, css)=>
    var line high_line = line.new(na,na,na,na
      , xloc = xloc.bar_time
      , color = css
      , style = get_line_style(pdhl_style))

    var label high_lbl = label.new(na,na
      , xloc = xloc.bar_time
      , text = str.format('P{0}H', tf)
      , color = TRANSP_CSS
      , textcolor = css
      , size = size.small
      , style = label.style_label_left)

    var line low_line = line.new(na,na,na,na
      , xloc = xloc.bar_time
      , color = css
      , style = get_line_style(pdhl_style))

    var label low_lbl = label.new(na,na
      , xloc = xloc.bar_time
      , text = str.format('P{0}L', tf)
      , color = TRANSP_CSS
      , textcolor = css
      , size = size.small
      , style = label.style_label_left)

    hy = ta.valuewhen(h != h[1], h, 1)
    hx = ta.valuewhen(h == high, time, 1)

    ly = ta.valuewhen(l != l[1], l, 1)
    lx = ta.valuewhen(l == low, time, 1)

    if barstate.islast
        ext = time + (time - time[1])*20

        //High
        line.set_xy1(high_line, hx, hy)
        line.set_xy2(high_line, ext, hy)

        label.set_xy(high_lbl, ext, hy)

        //Low
        line.set_xy1(low_line, lx, ly)
        line.set_xy2(low_line, ext, ly)

        label.set_xy(low_lbl, ext, ly)

//-----------------------------------------------------------------------------}
//Global variables
//-----------------------------------------------------------------------------{
var trend = 0, var itrend = 0

var top_y = 0., var top_x = 0
var btm_y = 0., var btm_x = 0

var itop_y = 0., var itop_x = 0
var ibtm_y = 0., var ibtm_x = 0

var trail_up = high, var trail_dn = low
var trail_up_x = 0,  var trail_dn_x = 0

var top_cross = true,  var btm_cross = true
var itop_cross = true, var ibtm_cross = true

var txt_top = '',  var txt_btm = ''

//Alerts
bull_choch_alert = false 
bull_bos_alert   = false 

bear_choch_alert = false 
bear_bos_alert   = false 

bull_ichoch_alert = false 
bull_ibos_alert   = false 

bear_ichoch_alert = false 
bear_ibos_alert   = false 

bull_iob_break = false 
bear_iob_break = false

bull_ob_break = false 
bear_ob_break = false

eqh_alert = false 
eql_alert = false 

//Structure colors
var bull_css = style == 'Monochrome' ? #b2b5be 
  : swing_bull_css

var bear_css = style == 'Monochrome' ? #b2b5be 
  : swing_bear_css

var ibull_css = style == 'Monochrome' ? #b2b5be 
  : swing_ibull_css

var ibear_css = style == 'Monochrome' ? #b2b5be 
  : swing_ibear_css

//Labels size
var internal_structure_lbl_size = internal_structure_size == 'Tiny' 
  ? size.tiny 
  : internal_structure_size == 'Small' 
  ? size.small 
  : size.normal 

var swing_structure_lbl_size = swing_structure_size == 'Tiny' 
  ? size.tiny 
  : swing_structure_size == 'Small' 
  ? size.small 
  : size.normal 

var eqhl_lbl_size = eq_size == 'Tiny' 
  ? size.tiny 
  : eq_size == 'Small' 
  ? size.small
  : size.normal 

//Swings
[top, btm] = swings(length)

[itop, ibtm] = swings(5)

//-----------------------------------------------------------------------------}
//Pivot High
//-----------------------------------------------------------------------------{
var line extend_top = na

var label extend_top_lbl = label.new(na, na
  , color = TRANSP_CSS
  , textcolor = bear_css
  , style = label.style_label_down
  , size = size.tiny)

if top
    top_cross := true
    txt_top := top > top_y ? 'HH' : 'LH'

    if show_swings
        top_lbl = label.new(n-length, top, txt_top
          , color = TRANSP_CSS
          , textcolor = bear_css
          , style = label.style_label_down
          , size = swing_structure_lbl_size)

        if mode == 'Present'
            label.delete(top_lbl[1])

    //Extend recent top to last bar
    line.delete(extend_top[1])
    extend_top := line.new(n-length, top, n, top
      , color = bear_css)

    top_y := top
    top_x := n - length

    trail_up := top
    trail_up_x := n - length

if itop
    itop_cross := true

    itop_y := itop
    itop_x := n - 5

//Trailing maximum
trail_up := math.max(high, trail_up)
trail_up_x := trail_up == high ? n : trail_up_x

//Set top extension label/line
if barstate.islast and show_hl_swings
    line.set_xy1(extend_top, trail_up_x, trail_up)
    line.set_xy2(extend_top, n + 20, trail_up)

    label.set_x(extend_top_lbl, n + 20)
    label.set_y(extend_top_lbl, trail_up)
    label.set_text(extend_top_lbl, trend < 0 ? 'Strong High' : 'Weak High')

//-----------------------------------------------------------------------------}
//Pivot Low
//-----------------------------------------------------------------------------{
var line extend_btm = na 

var label extend_btm_lbl = label.new(na, na
  , color = TRANSP_CSS
  , textcolor = bull_css
  , style = label.style_label_up
  , size = size.tiny)

if btm
    btm_cross := true
    txt_btm := btm < btm_y ? 'LL' : 'HL'
    
    if show_swings
        btm_lbl = label.new(n - length, btm, txt_btm
          , color = TRANSP_CSS
          , textcolor = bull_css
          , style = label.style_label_up
          , size = swing_structure_lbl_size)

        if mode == 'Present'
            label.delete(btm_lbl[1])
    
    //Extend recent btm to last bar
    line.delete(extend_btm[1])
    extend_btm := line.new(n - length, btm, n, btm
      , color = bull_css)

    btm_y := btm
    btm_x := n-length

    trail_dn := btm
    trail_dn_x := n-length

if ibtm
    ibtm_cross := true

    ibtm_y := ibtm
    ibtm_x := n - 5

//Trailing minimum
trail_dn := math.min(low, trail_dn)
trail_dn_x := trail_dn == low ? n : trail_dn_x

//Set btm extension label/line
if barstate.islast and show_hl_swings
    line.set_xy1(extend_btm, trail_dn_x, trail_dn)
    line.set_xy2(extend_btm, n + 20, trail_dn)

    label.set_x(extend_btm_lbl, n + 20)
    label.set_y(extend_btm_lbl, trail_dn)
    label.set_text(extend_btm_lbl, trend > 0 ? 'Strong Low' : 'Weak Low')

//-----------------------------------------------------------------------------}
//Order Blocks Arrays
//-----------------------------------------------------------------------------{
var iob_top = array.new_float(0)
var iob_btm = array.new_float(0)
var iob_left = array.new_int(0)
var iob_type = array.new_int(0)

var ob_top = array.new_float(0)
var ob_btm = array.new_float(0)
var ob_left = array.new_int(0)
var ob_type = array.new_int(0)

//-----------------------------------------------------------------------------}
//Pivot High BOS/CHoCH
//-----------------------------------------------------------------------------{
//Filtering
var bull_concordant = true

if ifilter_confluence
    bull_concordant := high - math.max(close, open) > math.min(close, open - low)

//Detect internal bullish Structure
if ta.crossover(close, itop_y) and itop_cross and top_y != itop_y and bull_concordant
    bool choch = na
    
    if itrend < 0
        choch := true
        bull_ichoch_alert := true
    else 
        bull_ibos_alert := true
    
    txt = choch ? 'CHoCH' : 'BOS'

    if show_internals
        if show_ibull == 'All' or (show_ibull == 'BOS' and not choch) or (show_ibull == 'CHoCH' and choch)
            display_Structure(itop_x, itop_y, txt, ibull_css, true, true, internal_structure_lbl_size)
    
    itop_cross := false
    itrend := 1
    
    //Internal Order Block
    if show_iob and showOrderBlocks
        ob_coord(false, itop_x, iob_top, iob_btm, iob_left, iob_type)

//Detect bullish Structure
if ta.crossover(close, top_y) and top_cross
    bool choch = na
    
    if trend < 0
        choch := true
        bull_choch_alert := true
    else 
        bull_bos_alert := true

    txt = choch ? 'CHoCH' : 'BOS'
    
    if show_Structure
        if show_bull == 'All' or (show_bull == 'BOS' and not choch) or (show_bull == 'CHoCH' and choch)
            display_Structure(top_x, top_y, txt, bull_css, false, true, swing_structure_lbl_size)
    
    //Order Block
    if show_ob and showOrderBlocks
        ob_coord(false, top_x, ob_top, ob_btm, ob_left, ob_type)

    top_cross := false
    trend := 1

//-----------------------------------------------------------------------------}
//Pivot Low BOS/CHoCH
//-----------------------------------------------------------------------------{
var bear_concordant = true

if ifilter_confluence
    bear_concordant := high - math.max(close, open) < math.min(close, open - low)

//Detect internal bearish Structure
if ta.crossunder(close, ibtm_y) and ibtm_cross and btm_y != ibtm_y and bear_concordant
    bool choch = false
    
    if itrend > 0
        choch := true
        bear_ichoch_alert := true
    else 
        bear_ibos_alert := true
    
    txt = choch ? 'CHoCH' : 'BOS'

    if show_internals
        if show_ibear == 'All' or (show_ibear == 'BOS' and not choch) or (show_ibear == 'CHoCH' and choch)
            display_Structure(ibtm_x, ibtm_y, txt, ibear_css, true, false, internal_structure_lbl_size)
    
    ibtm_cross := false
    itrend := -1
    
    //Internal Order Block
    if show_iob and showOrderBlocks
        ob_coord(true, ibtm_x, iob_top, iob_btm, iob_left, iob_type)

//Detect bearish Structure
if ta.crossunder(close, btm_y) and btm_cross
    bool choch = na
    
    if trend > 0
        choch := true
        bear_choch_alert := true
    else 
        bear_bos_alert := true

    txt = choch ? 'CHoCH' : 'BOS'
    
    if show_Structure
        if show_bear == 'All' or (show_bear == 'BOS' and not choch) or (show_bear == 'CHoCH' and choch)
            display_Structure(btm_x, btm_y, txt, bear_css, false, false, swing_structure_lbl_size)
    
    //Order Block
    if show_ob  and showOrderBlocks
        ob_coord(true, btm_x, ob_top, ob_btm, ob_left, ob_type)

    btm_cross := false
    trend := -1

//-----------------------------------------------------------------------------}
//Order Blocks
//-----------------------------------------------------------------------------{
//Set order blocks
var iob_boxes = array.new_box(0)
var ob_boxes = array.new_box(0)

//Delete internal order blocks box coordinates if top/bottom is broken
for element in iob_type
    index = array.indexof(iob_type, element)

    if close < array.get(iob_btm, index) and element == 1
        array.remove(iob_top, index) 
        array.remove(iob_btm, index) 
        array.remove(iob_left, index) 
        array.remove(iob_type, index)
        bull_iob_break := true

    else if close > array.get(iob_top, index) and element == -1
        array.remove(iob_top, index) 
        array.remove(iob_btm, index)
        array.remove(iob_left, index) 
        array.remove(iob_type, index)
        bear_iob_break := true

//Delete internal order blocks box coordinates if top/bottom is broken
for element in ob_type
    index = array.indexof(ob_type, element)

    if close < array.get(ob_btm, index) and element == 1
        array.remove(ob_top, index) 
        array.remove(ob_btm, index) 
        array.remove(ob_left, index) 
        array.remove(ob_type, index)
        bull_ob_break := true

    else if close > array.get(ob_top, index) and element == -1
        array.remove(ob_top, index) 
        array.remove(ob_btm, index)
        array.remove(ob_left, index) 
        array.remove(ob_type, index)
        bear_ob_break := true

iob_size = array.size(iob_type)
ob_size = array.size(ob_type)

if barstate.isfirst
    if show_iob and showOrderBlocks
        for i = 0 to iob_showlast-1
            array.push(iob_boxes, box.new(na,na,na,na, xloc = xloc.bar_time))
    if show_ob  and showOrderBlocks
        for i = 0 to ob_showlast-1
            array.push(ob_boxes, box.new(na,na,na,na, xloc = xloc.bar_time))

if iob_size > 0
    if barstate.islast
        display_ob(iob_boxes, iob_top, iob_btm, iob_left, iob_type, iob_showlast, false, iob_size)

if ob_size > 0
    if barstate.islast
        display_ob(ob_boxes, ob_top, ob_btm, ob_left, ob_type, ob_showlast, true, ob_size)

//-----------------------------------------------------------------------------}
//EQH/EQL
//-----------------------------------------------------------------------------{
var eq_prev_top = 0.
var eq_top_x = 0

var eq_prev_btm = 0.
var eq_btm_x = 0

if show_eq
    eq_top = ta.pivothigh(eq_len, eq_len)
    eq_btm = ta.pivotlow(eq_len, eq_len)

    if eq_top 
        max = math.max(eq_top, eq_prev_top)
        min = math.min(eq_top, eq_prev_top)
        
        if max < min + atr * eq_threshold
            eqh_line = line.new(eq_top_x, eq_prev_top, n-eq_len, eq_top
              , color = bear_css
              , style = line.style_dotted)

            eqh_lbl = label.new(int(math.avg(n-eq_len, eq_top_x)), eq_top, 'EQH'
              , color = #00000000
              , textcolor = bear_css
              , style = label.style_label_down
              , size = eqhl_lbl_size)

            if mode == 'Present'
                line.delete(eqh_line[1])
                label.delete(eqh_lbl[1])
            
            eqh_alert := true

        eq_prev_top := eq_top
        eq_top_x := n-eq_len

    if eq_btm 
        max = math.max(eq_btm, eq_prev_btm)
        min = math.min(eq_btm, eq_prev_btm)
        
        if min > max - atr * eq_threshold
            eql_line = line.new(eq_btm_x, eq_prev_btm, n-eq_len, eq_btm
              , color = bull_css
              , style = line.style_dotted)

            eql_lbl = label.new(int(math.avg(n-eq_len, eq_btm_x)), eq_btm, 'EQL'
              , color = #00000000
              , textcolor = bull_css
              , style = label.style_label_up
              , size = eqhl_lbl_size)

            eql_alert := true

            if mode == 'Present'
                line.delete(eql_line[1])
                label.delete(eql_lbl[1])

        eq_prev_btm := eq_btm
        eq_btm_x := n-eq_len

//-----------------------------------------------------------------------------}
//Fair Value Gaps
//-----------------------------------------------------------------------------{
var bullish_fvg_max = array.new_box(0)
var bullish_fvg_min = array.new_box(0)

var bearish_fvg_max = array.new_box(0)
var bearish_fvg_min = array.new_box(0)

float bullish_fvg_avg = na
float bearish_fvg_avg = na

bullish_fvg_cnd = false
bearish_fvg_cnd = false

[src_c1, src_o1, src_h, src_l, src_h2, src_l2] =
  request.security(syminfo.tickerid, fvg_tf, get_ohlc())

if show_fvg
    delta_per = (src_c1 - src_o1) / src_o1 * 100

    change_tf = timeframe.change(fvg_tf)

    threshold = fvg_auto ? ta.cum(math.abs(change_tf ? delta_per : 0)) / n * 2 
      : 0

    //FVG conditions
    bullish_fvg_cnd := src_l > src_h2
      and src_c1 > src_h2 
      and delta_per > threshold
      and change_tf

    bearish_fvg_cnd := src_h < src_l2 
      and src_c1 < src_l2 
      and -delta_per > threshold
      and change_tf

    //FVG Areas
    if bullish_fvg_cnd
        array.unshift(bullish_fvg_max, box.new(n-1, src_l, n + fvg_extend, math.avg(src_l, src_h2)
          , border_color = bull_fvg_css
          , bgcolor = bull_fvg_css))
        
        array.unshift(bullish_fvg_min, box.new(n-1, math.avg(src_l, src_h2), n + fvg_extend, src_h2
          , border_color = bull_fvg_css
          , bgcolor = bull_fvg_css))
    
    if bearish_fvg_cnd
        array.unshift(bearish_fvg_max, box.new(n-1, src_h, n + fvg_extend, math.avg(src_h, src_l2)
          , border_color = bear_fvg_css
          , bgcolor = bear_fvg_css))
        
        array.unshift(bearish_fvg_min, box.new(n-1, math.avg(src_h, src_l2), n + fvg_extend, src_l2
          , border_color = bear_fvg_css
          , bgcolor = bear_fvg_css))

    for bx in bullish_fvg_min
        if low < box.get_bottom(bx)
            box.delete(bx)
            box.delete(array.get(bullish_fvg_max, array.indexof(bullish_fvg_min, bx)))
    
    for bx in bearish_fvg_max
        if high > box.get_top(bx)
            box.delete(bx)
            box.delete(array.get(bearish_fvg_min, array.indexof(bearish_fvg_max, bx)))

//-----------------------------------------------------------------------------}
//Previous day/week high/lows
//-----------------------------------------------------------------------------{
//Daily high/low
[pdh, pdl] = request.security(syminfo.tickerid, 'D', hl()
  , lookahead = barmerge.lookahead_on)

//Weekly high/low
[pwh, pwl] = request.security(syminfo.tickerid, 'W', hl()
  , lookahead = barmerge.lookahead_on)

//Monthly high/low
[pmh, pml] = request.security(syminfo.tickerid, 'M', hl()
  , lookahead = barmerge.lookahead_on)

//Display Daily
if show_pdhl
    phl(pdh, pdl, 'D', pdhl_css)

//Display Weekly
if show_pwhl
    phl(pwh, pwl, 'W', pwhl_css)
    
//Display Monthly
if show_pmhl
    phl(pmh, pml, 'M', pmhl_css)

//-----------------------------------------------------------------------------}
//Premium/Discount/Equilibrium zones
//-----------------------------------------------------------------------------{
var premium = box.new(na, na, na, na
  , bgcolor = color.new(premium_css, 80)
  , border_color = na)

var premium_lbl = label.new(na, na
  , text = 'Premium'
  , color = TRANSP_CSS
  , textcolor = premium_css
  , style = label.style_label_down
  , size = size.small)

var eq = box.new(na, na, na, na
  , bgcolor = color.rgb(120, 123, 134, 80)
  , border_color = na)

var eq_lbl = label.new(na, na
  , text = 'Equilibrium'
  , color = TRANSP_CSS
  , textcolor = eq_css
  , style = label.style_label_left
  , size = size.small)

var discount = box.new(na, na, na, na
  , bgcolor = color.new(discount_css, 80)
  , border_color = na)

var discount_lbl = label.new(na, na
  , text = 'Discount'
  , color = TRANSP_CSS
  , textcolor = discount_css
  , style = label.style_label_up
  , size = size.small)

//Show Premium/Discount Areas
if barstate.islast and show_sd
    avg = math.avg(trail_up, trail_dn)

    box.set_lefttop(premium, math.max(top_x, btm_x), trail_up)
    box.set_rightbottom(premium, n, .95 * trail_up + .05 * trail_dn)

    label.set_xy(premium_lbl, int(math.avg(math.max(top_x, btm_x), n)), trail_up)

    box.set_lefttop(eq, math.max(top_x, btm_x), .525 * trail_up + .475*trail_dn)
    box.set_rightbottom(eq, n, .525 * trail_dn + .475 * trail_up)

    label.set_xy(eq_lbl, n, avg)
    
    box.set_lefttop(discount, math.max(top_x, btm_x), .95 * trail_dn + .05 * trail_up)
    box.set_rightbottom(discount, n, trail_dn)
    label.set_xy(discount_lbl, int(math.avg(math.max(top_x, btm_x), n)), trail_dn)

//-----------------------------------------------------------------------------}
//Trend
//-----------------------------------------------------------------------------{
var color trend_css = na

if show_trend
    if style == 'Colored'
        trend_css := itrend == 1 ? bull_css : bear_css
    else if style == 'Monochrome'
        trend_css := itrend == 1 ? #b2b5be : #5d606b

plotcandle(open, high, low, close
  , color = trend_css
  , wickcolor = trend_css
  , bordercolor = trend_css
  , editable = false)

//-----------------------------------------------------------------------------}
//Alerts
//-----------------------------------------------------------------------------{
//Internal Structure
alertcondition(bull_ibos_alert, 'Internal Bullish BOS', 'Internal Bullish BOS formed')
alertcondition(bull_ichoch_alert, 'Internal Bullish CHoCH', 'Internal Bullish CHoCH formed')

alertcondition(bear_ibos_alert, 'Internal Bearish BOS', 'Internal Bearish BOS formed')
alertcondition(bear_ichoch_alert, 'Internal Bearish CHoCH', 'Internal Bearish CHoCH formed')

//Swing Structure
alertcondition(bull_bos_alert, 'Bullish BOS', 'Internal Bullish BOS formed')
alertcondition(bull_choch_alert, 'Bullish CHoCH', 'Internal Bullish CHoCH formed')

alertcondition(bear_bos_alert, 'Bearish BOS', 'Bearish BOS formed')
alertcondition(bear_choch_alert, 'Bearish CHoCH', 'Bearish CHoCH formed')

//order Blocks
// alertcondition(bull_iob_break, 'Bullish Internal OB Breakout', 'Price broke bullish internal OB')
// alertcondition(bear_iob_break, 'Bearish Internal OB Breakout', 'Price broke bearish internal OB')

// alertcondition(bull_ob_break, 'Bullish Swing OB Breakout', 'Price broke bullish swing OB')
// alertcondition(bear_ob_break, 'Bearish Swing OB Breakout', 'Price broke bearish swing OB')

//EQH/EQL
// alertcondition(eqh_alert, 'Equal Highs', 'Equal highs detected')
// alertcondition(eql_alert, 'Equal Lows', 'Equal lows detected')

//FVG
alertcondition(bullish_fvg_cnd, 'Bullish FVG', 'Bullish FVG formed')
alertcondition(bearish_fvg_cnd, 'Bearish FVG', 'Bearish FVG formed')

//-----------------------------------------------------------------------------}


